name: teste de workflow

on: pull_request


jobs:
  teste-continuo:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v3
    - name: usando php
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4
    - name: starter
      run: | 
          npm install
          npm run build
          npm run teste